### ISSUE TITLE
Make compatible with `semantic-release` 11.x plugin system

### ISSUE THREAD

**Issue by pmowrer** [bahmutov/simple-commit-message#21]
Old plugin format (as of this writing, still referenced as current in the `semantic-release` README):

`function (pluginConfig, config, callback)`

New format:
`async function (pluginConfig, config)`
or
`function (pluginConfig, config)` returning `Promise`

https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0

**Comment by bahmutov** [comment]
Hmm, trying to release, but hitting but in semantic release itself
```
[Semantic release]: An error occurred while running semantic-release: TypeError: Cannot read property 'log' of undefined
    at module.exports (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/normalize.js:17:14)
    at plugins.(anonymous function).pluginConfs.map.conf (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/index.js:27:42)
    at Array.map (<anonymous>)
```

**Comment by bahmutov** [comment]
another failing example in this build https://travis-ci.org/bahmutov/cypress-cycle-unit-test/builds/341285055
```
[Semantic release]: No version found of package cypress-cycle-unit-test found on http://registry.npmjs.org/
[Semantic release]: No previous release found, retrieving all commits
[Semantic release]: Found 9 commits since last release
[Semantic release]: Call plugin analyze-commits
found 8 semantic commit(s)
[ { firstLine: 'feat: http example, close #1',
    type: 'feat',
    scope: undefined,
    subject: 'http example, close #1' },
  { firstLine: 'chore: format specs',
    type: 'chore',
    scope: undefined,
    subject: 'format specs' },
  { firstLine: 'chore: add TypeScript support',
    type: 'chore',
    scope: undefined,
    subject: 'add TypeScript support' },
  { firstLine: 'chore: add counter spec',
    type: 'chore',
    scope: undefined,
    subject: 'add counter spec' },
  { firstLine: 'chore: add checkbox spec',
    type: 'chore',
    scope: undefined,
    subject: 'add checkbox spec' },
  { firstLine: 'chore: setup semantic release',
    type: 'chore',
    scope: undefined,
    subject: 'setup semantic release' },
  { firstLine: 'chore: hello world spec',
    type: 'chore',
    scope: undefined,
    subject: 'hello world spec' },
  { firstLine: 'chore: initial code',
    type: 'chore',
    scope: undefined,
    subject: 'initial code' } ]
[Semantic release]: An error occurred while running semantic-release: TypeError: cb is not a function
    at analyzeCommits (/home/travis/build/bahmutov/cypress-cycle-unit-test/node_modules/simple-commit-message/src/analyze-commits.js:34:3)
    at simple (eval at <anonymous> (/home/travis/build/bahmutov/cypress-cycle-unit-test/node_modules/simple-commit-message/src/index.js:12:17), <anonymous>:2:25)
    at Object.analyzeCommits (/home/travis/build/bahmutov/cypress-cycle-unit-test/node_modules/semantic-release/lib/plugins/normalize.js:41:26)
    at run (/home/travis/build/bahmutov/cypress-cycle-unit-test/node_modules/semantic-release/index.js:54:30)
    at <anonymous>
```

versions
```
"semantic-release": "^12.4.1"
$ npm ls simple-commit-message
cypress-cycle-unit-test@0.0.0-development /Users/gleb/git/cypress-cycle-unit-test
└─┬ pre-git@3.17.0
  └── simple-commit-message@3.3.2 
```
