### ISSUE TITLE
Fix release

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/simple-commit-message#24]
Currently getting the following error when trying to release a new version, see https://travis-ci.org/bahmutov/simple-commit-message

```
[13:32:09] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "simple-commit-message"
[13:32:09] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: cb is not a function
    at analyzeCommits (/home/travis/build/bahmutov/simple-commit-message/node_modules/simple-commit-message/src/analyze-commits.js:34:3)
    at simple (eval at <anonymous> (/home/travis/build/bahmutov/simple-commit-message/node_modules/simple-commit-message/src/index.js:12:17), <anonymous>:2:25)
    at validator (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/bahmutov/simple-commit-message/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) pluginName: 'simple-commit-message' }
{ TypeError: cb is not a function
    at analyzeCommits (/home/travis/build/bahmutov/simple-commit-message/node_modules/simple-commit-message/src/analyze-commits.js:34:3)
    at simple (eval at <anonymous> (/home/travis/build/bahmutov/simple-commit-message/node_modules/simple-commit-message/src/index.js:12:17), <anonymous>:2:25)
    at validator (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/travis/build/bahmutov/simple-commit-message/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/bahmutov/simple-commit-message/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) pluginName: 'simple-commit-message' }npm ERR! code ELIFECYCLE
```

**Comment by bahmutov** [comment]
done
